metadata:
  name: Myservice
  team: MyTeam
  env: development
cloud: gcp
account: project
region: us-west2
components:
  - Network:
    create: false
    network: morning
    subnet: mon
  - Storage:
      name: MTestRandomStorage
